export const GET_PRODUCTS = "GET_PRODUCTS";
export const TOGGLE_PRODUCTS_LOADING = "TOGGLE_PRODUCTS_LOADING";
export const TOGGLE_PRODUCTS_ERROR = "TOGGLE_PRODUCTS_ERROR";
export const ADD_PRODUCT_TO_FAVS = "ADD_PRODUCT_TO_FAVS";
export const REMOVE_PRODUCT_FROM_FAVS = "REMOVE_PRODUCT_FROM_FAVS";
